### ISSUE TITLE
How to integrate this in HA ?

### ISSUE THREAD

**Issue by molusk** [mag1024/epson-projector-modern-homeassistant#1]
Hi,

I wanted to test your code in my HA instance with a LS12000 but without guidance about the configuration I am a bit stuck...

I downloaded the sub-directory and put it in my HA config along with my other custom integrations. Then modifyied my configuration.yaml file to add the projector (I did not find the integration in the UI) but then nothing... 
YAML parser says everything is fine, so the custom integration is known.
Maybe I am missing a parameter in the YAML file ?

```
epson_projector_modern:
  host: epson_projector_hostname
  name: Projo Epson
````

The same configuration works well with PJLink, so the issue is not with the DNS name.

Thank you.

**Comment by mag1024** [comment]
Hey -- it should should show up in the UI, under the name "Epson Projector (Modern)"
For the installation simply dropping the *epson_projector_modern* sub-directory (not the top-level *epson-projector-modern-homeassistant* directory) into the *config/custom_components/* of your HA installation should do the trick.
(You may alternatively be able to add it as a custom repository to HACS, but I haven't tested this route)
If you've done that, but the integration doesn't show up, perhaps some error occurs at initialization time. Is there anything information in the HA logs? (Go to *Load Full Logs*, and search for *epson_projector_modern*).

**Comment by molusk** [comment]
Ok, my bad, it does show up in the UI !
It must have been an issue with my browser cache the first time I tried...

Anyway, it is a valid simple replacement for PJLink, thank you.
For the moment, I just need to be able to turn it on and off, so this is perfect !
Thank's for your work :)
